export default {
  Cage: {},
  Grotto: {},
  Guardian: {},
  Haven: {},
  Lighthouse: {},
  Search: {},
  Amulet: {},
  Astrolabe: {},
  "Caravan Guard": {},
  "Cargo Ship": {},
  Church: {},
  Dungeon: {},
  Enchantress: {},
  "Fishing Village": {},
  Gear: {
    // Puts into setAside on play
    // <pNick> sets <card(s)> aside with Gear.
    // Puts into hand on turn start...
    // <pNick> puts <card(s)> in hand (Gear).,
  },
  "Ghost Town": {},
  Importer: {},
  Monkey: {},
  "Secluded Shrine": {},
  "Secret Cave": {},
  Siren: {},
  Stowaway: {},
  Taskmaster: {},
  Abundance: {},
  Blockade: {},
  "Cabin Boy": {},
  Caravan: {},
  Conjurer: {},
  Flagship: {},
  Garrison: {},
  "Landing Party": {},
  Research: {},
  "Royal Galley": {},
  Sailor: {},
  "Tide Pools": {},
  "Village Green": {},
  Voyage: {},
  Rope: {},
  Ghost: {},
  Archive: {},
  Barge: {},
  "Bridge Troll": {},
  "Buried Treasure": {},
  Cobbler: {},
  Contract: {},
  Corsair: {},
  Crew: {},
  Crypt: {},
  Cutthroat: {},
  "Den of Sin": {},
  Enlarge: {},
  Frigate: {},
  Gatekeeper: {},
  "Haunted Woods": {},
  Highwayman: {},
  Longship: {},
  Mastermind: {
    // plays any card 3 times
  },
  "Merchant Ship": {},
  Outpost: {},
  Pirate: {},
  Quartermaster: {},
  "Sea Witch": {},
  "Swamp Hag": {},
  Tactician: {},
  Warlord: {},
  Wharf: {},
  Captain: {},
  Hireling: {},
  Raider: {},
  Stronghold: {},
  Champion: {},
  Amphora: {},
  "Endless Chalice": {},
  Figurehead: {},
  Jewels: {},
  Prince: {},
};
