export const duration_constants: {
  [title: string]: { LIFESPAN: number | undefined };
} = {
  Cage: { LIFESPAN: undefined },
  Grotto: { LIFESPAN: 1 },
  Guardian: { LIFESPAN: undefined },
  Haven: { LIFESPAN: 1 },
  Lighthouse: { LIFESPAN: undefined },
  Search: { LIFESPAN: undefined },
  Amulet: { LIFESPAN: 1 },
  Astrolabe: { LIFESPAN: 1 },
  "Caravan Guard": { LIFESPAN: undefined },
  "Cargo Ship": { LIFESPAN: undefined },
  Church: { LIFESPAN: undefined },
  Dungeon: { LIFESPAN: 1 },
  Enchantress: { LIFESPAN: undefined },
  "Fishing Village": { LIFESPAN: 1 },
  Gear: {
    LIFESPAN: 1,
    // Puts into setAside on play
    // <pNick> sets <card(s)> aside with Gear.
    // Puts into hand on turn start...
    // <pNick> puts <card(s)> in hand (Gear).,
  },
  "Ghost Town": { LIFESPAN: undefined },
  Importer: { LIFESPAN: undefined },
  Monkey: { LIFESPAN: undefined },
  "Secluded Shrine": { LIFESPAN: undefined },
  "Secret Cave": { LIFESPAN: undefined },
  Siren: { LIFESPAN: undefined },
  Stowaway: { LIFESPAN: undefined },
  Taskmaster: { LIFESPAN: undefined },
  Abundance: { LIFESPAN: undefined },
  Blockade: { LIFESPAN: undefined },
  "Cabin Boy": { LIFESPAN: 1 },
  Caravan: { LIFESPAN: 1 },
  Conjurer: { LIFESPAN: undefined },
  Flagship: { LIFESPAN: undefined },
  Garrison: { LIFESPAN: undefined },
  "Landing Party": { LIFESPAN: undefined },
  Research: { LIFESPAN: undefined },
  "Royal Galley": { LIFESPAN: undefined },
  Sailor: { LIFESPAN: undefined },
  "Tide Pools": { LIFESPAN: undefined },
  "Village Green": { LIFESPAN: undefined },
  Voyage: { LIFESPAN: undefined },
  Rope: {
    LIFESPAN: 1,
  },
  Ghost: { LIFESPAN: undefined },
  Archive: { LIFESPAN: undefined },
  Barge: { LIFESPAN: undefined },
  "Bridge Troll": { LIFESPAN: undefined },
  "Buried Treasure": { LIFESPAN: undefined },
  Cobbler: { LIFESPAN: undefined },
  Contract: { LIFESPAN: undefined },
  Corsair: { LIFESPAN: undefined },
  Crew: { LIFESPAN: undefined },
  Crypt: { LIFESPAN: undefined },
  Cutthroat: { LIFESPAN: undefined },
  "Den of Sin": { LIFESPAN: undefined },
  Enlarge: { LIFESPAN: undefined },
  Frigate: { LIFESPAN: undefined },
  Gatekeeper: { LIFESPAN: undefined },
  "Haunted Woods": { LIFESPAN: undefined },
  Highwayman: { LIFESPAN: undefined },
  Longship: { LIFESPAN: undefined },
  Mastermind: {
    LIFESPAN: undefined,
    // plays any card 3 times
  },
  "Merchant Ship": { LIFESPAN: undefined },
  Outpost: { LIFESPAN: undefined },
  Pirate: { LIFESPAN: undefined },
  Quartermaster: { LIFESPAN: undefined },
  "Sea Witch": { LIFESPAN: undefined },
  "Swamp Hag": { LIFESPAN: undefined },
  Tactician: { LIFESPAN: undefined },
  Warlord: { LIFESPAN: undefined },
  Wharf: { LIFESPAN: undefined },
  Captain: { LIFESPAN: undefined },
  Hireling: { LIFESPAN: undefined },
  Raider: { LIFESPAN: undefined },
  Stronghold: { LIFESPAN: undefined },
  Champion: { LIFESPAN: undefined },
  Amphora: { LIFESPAN: undefined },
  "Endless Chalice": { LIFESPAN: undefined },
  Figurehead: { LIFESPAN: undefined },
  Jewels: { LIFESPAN: undefined },
  Prince: { LIFESPAN: undefined },
};
